### ISSUE TITLE
Documentation error in "What is a Stamp"

### ISSUE THREAD

**Issue by mlrsoft** [stampit-org/docs#1]
### Documentation Error
In https://github.com/stampit-org/docs/blob/master/essentials/what-is-a-stamp.md there is a minor error under the heading 
### Ducktyping a stamp
```
function isStamp (object) {
  return typeof object === 'function' && object.compose === 'function'
}
```
is missing `typeof` before `object.compose === 'function'`
```
function isStamp (object) {
  return typeof object === 'function' && typeof object.compose === 'function'
}
```

**Comment by koresar** [comment]
Fixed. Thank you very much!
